### ISSUE TITLE
[BUG]: Vector UDF doesn't work in databricks environment

### ISSUE THREAD

**Issue by grazy27** [dotnet/spark#1214]
# Vector UDF Incompatibility in Databricks Environment

## Background
Code in dotnet.spark.worker, when parses binary stream, expects for a single large Arrow batch or data. 
However, for Databricks Runtime 15.3 (As i understant, for any linux env), behavior differs, as driver dataset divided by multiple batches, 10k rows in each. 
This format uses different binary format(It has more arguments) 
Due to differing binary representations, it misinterprets incoming byte streams—reading incorrect data, resulting in a hang with no response.

## Reproduction
Create a Spark pipeline that:
* Ingests a moderate-sized dataset.
* Performs a GroupBy (ensure groups contain >10k rows).
* Applies a vector UDF via GroupBy().Apply(...), operating on the grouped RecordBatch.

### Actual results
The UDF execution never completes. The .NET Spark worker attempts to read more bytes than are available, blocking indefinitely while waiting for data that is never sent.

### Expected result
UDF should execute and return successfully.

TBD: Either a single consolidated RecordBatch or an IEnumerable<RecordBatch> should be passed into the UDF.

## Investigation Summary

The spark.sql.execution.arrow.maxRecordsPerBatch setting, introduced in Spark 2.3.0 (default: 10,000), plays a key role. Overall using batches is beneficial for .NET Spark, as it can circumvent the 2GB Arrow buffer limit per group when using GroupBy().Apply(...).

I implemented a PoC to validate performance for a specific use case. It successfully resolves the issue with the following changes:

* The vector UDF now accepts IEnumerable<RecordBatch>.
* Several new parameters are queried but ignored. In the Python implementation, these are used to maintain batch ordering. In my testing, batches always arrive sequentially, so ordering logic was omitted.

### References:
* [PoC Commit](https://github.com/grazy27/spark/commit/3b8d14b541efd0193cec07f374fb69dd92577538), see SqlCommandExecutor::ExecuteArrowGroupedMapCommand

* [Arrow Sending Logic](https://github.com/apache/spark/blob/702738bb8f596f445b7141a3779637efd1107c4a/sql/core/src/main/scala/org/apache/spark/sql/execution/arrow/ArrowConverters.scala)

### Notes:
* CoGroupedMap UDFs are unaffected as they do not leverage batching (as of Spark 3.5).
* Databricks runtime 16.3 doesn't work with dotnet.spark entirely, so no testing is performed on it.

**Comment by wudanzy** [comment]
We may need to allow different format, so user can make that depending on the runtime.

BTW, does Databricks runtime 16.3 support pyspark? I think spark.NET just mimic pyspark, so from spark's view point it looks like a pyspark job, except the entry point is different.

**Comment by grazy27** [comment]
@wudanzy Hello,
PySpark remains a top-priority language for Databricks and will continue to be supported and extended.

From Spark's perspective, it interacts with PySpark via the CreatePythonFunction method, which launches a specified executable with given arguments, initiating socket communication, etc.

However, in DBR 15.3, 16.3, this method is no longer accessible via the dotnet-spark JAR. It still works in DBR 14.3, even though both use Spark 3.5. This suggests Databricks may have modified or replaced the implementation, or changed its signature.
```
[Error] [JvmBridge] JVM method execution failed: Static method 'createPythonFunction' failed for class 'org.apache.spark.sql.api.dotnet.SQLUtils' when called with 7 arguments ([Index=1, Type=Byte[], Value=System.Byte[]], [Index=2, Type=Hashtable, Value=Microsoft.Spark.Interop.Internal.Java.Util.Hashtable], [Index=3, Type=ArrayList, Value=Microsoft.Spark.Interop.Internal.Java.Util.ArrayList], [Index=4, Type=String, Value=Microsoft.Spark.Worker], [Index=5, Type=String, Value=2.1.1.0], [Index=6, Type=ArrayList, Value=Microsoft.Spark.Interop.Internal.Java.Util.ArrayList], [Index=7, Type=null, Value=null])
[2024-09-13T10:47:53.1569404Z] [machine] [Error] [JvmBridge] java.lang.NoSuchMethodError: org.apache.spark.api.python.SimplePythonFunction.<init>(Lscala/collection/Seq;Ljava/util/Map;Ljava/util/List;Ljava/lang/String;Ljava/lang/String;Ljava/util/List;Lorg/apache/spark/api/python/PythonAccumulatorV2;)V
	at org.apache.spark.sql.api.dotnet.SQLUtils$.createPythonFunction(SQLUtils.scala:35)
	at org.apache.spark.sql.api.dotnet.SQLUtils.createPythonFunction(SQLUtils.scala)
```
To confirm, we’d need to extract and inspect the Databricks-specific Spark JARs from the environment.

Given Databricks’ ongoing investment in PySpark, we should anticipate regular breaking changes. If this project is to continue actively, Microsoft and Databricks will likely need to align on source sharing to streamline development.

**Comment by davinder-veeam** [comment]
I am facing similar issue with `15.x` and `16.x` LTS releases as well. (incase someone needed that info)

**Comment by davinder-veeam** [comment]
similar issue: https://github.com/dotnet/spark/issues/1220

**Comment by wudanzy** [comment]
Hi @grazy27, thanks for the investigation! Do you know how does DBR 15.3, 16.3 work with python? If we know how it works in Databracks, we can mimic that.

Our team focuses on internal teams, and we don't have a channel with Databracks.
